/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.panels;

import daos.IAdresse;
import daos.IEvenement;
import daos.IPays;
import daos.IVille;
import java.awt.Dimension;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import main.*;
import javax.swing.JOptionPane;
import main.adminpage.DashResumeForm;
import models.Adresses;
import models.Evenements;
import models.Pays;
import models.Utilisateurs;
import models.Villes;
import services.AdresseService;
import services.EvenementService;
import services.PaysService;
import services.VilleService;

/**
 *
 * @author user
 */
public class EventPanelAdd extends javax.swing.JPanel {

    public Utilisateurs userInfo;
    public Evenements event;
    
    Layout _layout = new Layout();
    
    IEvenement ie = new EvenementService();
    IVille iv = new VilleService();
    IPays ip = new PaysService();
    IAdresse ia = new AdresseService();

    /**
     * Creates new form AdminAddEvent
     */
    public EventPanelAdd() {
        initComponents();
        
        _layout.loadCombo(ip.pays(), jfEventPays, "name");
        jfEventVille.setEnabled(false);
    }

    private Evenements getFieldsValue() {
        String _title = jfEventTitle.getText();
        String _desc = jfEventDesc.getText();
        String _adresse = jfEventAdresse.getText();
        String _adresse2 = jfEventAdresse2.getText();
        String _zip = jfEventZip.getText();
        
        
        
        SimpleDateFormat inputFormatter = new SimpleDateFormat("EEE MMM dd HH:mm:ss zzz yyyy", Locale.US);
        
        String dateFinFormat = ""; 
        String dateDebutFormat = "";
        
        
        try {
            String _dateDebut = jfEventDebut.getValue().toString();
            Date dateD = inputFormatter.parse(_dateDebut);
            DateFormat outputFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm");
            dateDebutFormat = outputFormat.format(dateD);
        } catch (ParseException ex) {
            Logger.getLogger(EventPanelAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            String _dateFin = jfEventFin.getValue().toString();
            Date dateF = inputFormatter.parse(_dateFin);
            DateFormat outputFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm");
            dateFinFormat = outputFormat.format(dateF);
        } catch (ParseException ex) {
            Logger.getLogger(EventPanelAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String _villeName = jfEventVille.getSelectedItem().toString();
        
        Date _dateDebut = new Date(); Date _dateFin  = new Date();
        
        System.out.println(_title + " - " + _desc + " - " + _adresse + " - " + dateDebutFormat + " - " + dateFinFormat);
        
        System.out.println(userInfo);
        
        // get ville by ville name
        Adresses addr = new Adresses();
        addr.setAdresse1(_adresse);
        addr.setAdresse2(_adresse2);
        addr.setCodePostal(_zip);
        addr.setVilleId(iv.getVilleByName(_villeName));
        
        Adresses adrs = ia.addAdresses(addr); 
        
        Evenements evnt = new Evenements(_title, _desc, _dateDebut, _dateFin);
        evnt.setAdresseId(adrs);
        evnt.setOrganisateurId(userInfo);
        
        ie.addEvent(evnt); // save event
        
        System.out.println(evnt);
        return evnt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jfBtnModifier = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jfEventVille = new javax.swing.JComboBox<>();
        jfEventPays = new javax.swing.JComboBox<>();
        jfEventDebut = new javax.swing.JSpinner();
        jfEventFin = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jfEventDesc = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jfEventTitle = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jfEventAdresse = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jfEventAdresse2 = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jfEventZip = new javax.swing.JTextPane();

        jLabel1.setText("Titre");

        jLabel2.setText("Description");

        jfBtnModifier.setText("Ajouter");
        jfBtnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfBtnModifierActionPerformed(evt);
            }
        });

        jLabel3.setText("Date et Heure de début");

        jLabel4.setText("Date et Heure de fin");

        jLabel5.setText("Adresse");

        jLabel6.setText("Ville");

        jLabel7.setText("Pays");

        jfEventVille.setEditable(true);
        jfEventVille.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1" }));
        jfEventVille.setFocusable(false);

        jfEventPays.setEditable(true);
        jfEventPays.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1" }));
        jfEventPays.setFocusable(false);
        jfEventPays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfEventPaysActionPerformed(evt);
            }
        });

        jfEventDebut.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR));
        jfEventDebut.setFocusable(false);

        jfEventFin.setModel(new javax.swing.SpinnerDateModel());
        jfEventFin.setFocusable(false);

        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jfEventDesc);

        jScrollPane2.setViewportView(jfEventTitle);

        jScrollPane3.setViewportView(jfEventAdresse);

        jLabel8.setText("Adresse 2  (optionnel)");

        jScrollPane4.setViewportView(jfEventAdresse2);

        jLabel9.setText("Code Zip");

        jScrollPane5.setViewportView(jfEventZip);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jfEventPays, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addGap(25, 25, 25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jfEventVille, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(89, 89, 89)
                            .addComponent(jfBtnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane5))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jfEventDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jfEventFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jfEventDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jfEventFin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jfEventPays, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jfEventVille, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jfBtnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jfBtnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfBtnModifierActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Holla holla");
        Evenements ev = getFieldsValue();
        System.out.println(ev);
        
        /*jfEventTitle.setEditable(true);
        jfEventTitle.setEnabled(true);
        
        jfEventDesc.setEditable(true);
        jfEventDesc.setEnabled(true);
        
        jfEventDebut.setEnabled(true);
        jfEventFin.setEnabled(true);
        
        jfEventAdresse1.setEditable(true);
        jfEventAdresse1.setEnabled(true);
        jfEventAdresse1.setFocusable(true);

        jfEventAdresse2.setEditable(true);
        jfEventAdresse2.setEnabled(true);
        jfEventAdresse2.setFocusable(true);
        
        jfEventVille.setEditable(true);
        jfEventVille.setEnabled(true);
        
        jfEventPays.setEditable(true);
        jfEventPays.setEnabled(true);
        
        event.setTitre(jfEventTitle.getText());
        
        updateEvent();
        jfBtnModifier.setText("Mettre à jour");*/
        
    }//GEN-LAST:event_jfBtnModifierActionPerformed

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jfEventPaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfEventPaysActionPerformed
        // TODO add your handling code here:
        if(!jfEventPays.getSelectedItem().toString().contains("---")){
            jfEventVille.setEnabled(true);
            String _paysName = jfEventPays.getSelectedItem().toString();
            Pays _pays = ip.getPaysByName(_paysName);
            int _paysId = Integer.valueOf(_pays.getId());
            
            List<Villes> _villes = iv.getVillesByPaysId(_paysId);
            
            _layout.loadCombo(_villes, jfEventVille, "name");
        }else{
            jfEventVille.setEnabled(false);
        }
    }//GEN-LAST:event_jfEventPaysActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jfBtnModifier;
    private javax.swing.JTextPane jfEventAdresse;
    private javax.swing.JTextPane jfEventAdresse2;
    private javax.swing.JSpinner jfEventDebut;
    private javax.swing.JTextPane jfEventDesc;
    private javax.swing.JSpinner jfEventFin;
    private javax.swing.JComboBox<String> jfEventPays;
    private javax.swing.JTextPane jfEventTitle;
    private javax.swing.JComboBox<String> jfEventVille;
    private javax.swing.JTextPane jfEventZip;
    // End of variables declaration//GEN-END:variables
}
