/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.panels;

import daos.IUtilisateur;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.Evenements;
import models.Utilisateurs;
import services.UtilisateurService;

/**
 *
 * @author user
 */
public class UserPanelDetails extends javax.swing.JPanel {

    public Utilisateurs user;
    IUtilisateur iu = new UtilisateurService();

    /**
     * Creates new form UserPanelDetails
     */
    public UserPanelDetails(int id) {
        try {
            user = iu.findUserById(id);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

        initComponents();
        disableOrEnableFields(false);
        // JOptionPane.showMessageDialog(null, "Heelo, user details");

        setFieldsUserValue(user);
        System.out.println("UserPanelDetails");
    }

    private void disableOrEnableFields(boolean state) {
        System.out.println("Disable fields");
        jfUserPrenom.setEnabled(state);
        jfUserPrenom.setEditable(state);

        jfUserNom.setEnabled(state);
        jfUserNom.setEditable(state);

        jfUserEmail.setEnabled(state);
        jfUserEmail.setEditable(state);

        jfUserTelephone.setEnabled(state);
        jfUserTelephone.setEditable(state);

        jfUserPassword.setEnabled(state);
        jfUserPassword.setEditable(state);

        jfUserRole.setEnabled(state);
        jfUserRole.setEditable(state);
    }

    private void setFieldsUserValue(Utilisateurs u) {
        System.out.println("Set fields value");
        disableOrEnableFields(false);

        jfUserPrenom.setText(u.getPrenom());
        jfUserNom.setText(u.getNom());
        jfUserEmail.setText(u.getEmail());
        jfUserTelephone.setText(u.getTelephone());
        jfUserPassword.setText(u.getEmail());
        jfUserRole.setSelectedItem(u.getRole());

        boolean isActif = (u.getActive() == true) ? true : false;

        jfUserActif.setSelected(isActif);

        SimpleDateFormat formatter = new SimpleDateFormat("EEE MMM dd HH:mm:ss zzz yyyy", Locale.US);

        try {
            Date dateModification = new Date();
            Date dateModificationFormat = formatter.parse(dateModification.toString());

        } catch (ParseException ex) {
            Logger.getLogger(EventPanelDetails.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jfUserNom = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jfUserPrenom = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jfUserEmail = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jfUserTelephone = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jfUserRole = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jfUserPassword = new javax.swing.JTextPane();
        jfUserActif = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jfBtnModifier = new javax.swing.JButton();

        jLabel1.setText("Prenom");

        jLabel2.setText("Nom");

        jScrollPane2.setViewportView(jfUserNom);

        jScrollPane3.setViewportView(jfUserPrenom);

        jLabel3.setText("Email");

        jLabel4.setText("Téléphone");

        jScrollPane1.setViewportView(jfUserEmail);

        jScrollPane4.setViewportView(jfUserTelephone);

        jLabel5.setText("Mot de passe");

        jLabel6.setText("Role");

        jfUserRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));

        jScrollPane5.setViewportView(jfUserPassword);

        jfUserActif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfUserActifActionPerformed(evt);
            }
        });

        jLabel7.setText("Compte actif ?");

        jfBtnModifier.setText("Modifier");
        jfBtnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfBtnModifierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jfUserRole, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfBtnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jfUserActif)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))))
                .addContainerGap(328, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jfUserRole, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jfUserActif))))
                .addGap(8, 8, 8)
                .addComponent(jfBtnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jfUserActifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfUserActifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfUserActifActionPerformed

    private void jfBtnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfBtnModifierActionPerformed
        // TODO add your handling code here:
        disableOrEnableFields(true);

        updateUser(user);
        jfBtnModifier.setText("Mettre à jour");
    }//GEN-LAST:event_jfBtnModifierActionPerformed

    private void updateUser(Utilisateurs user) {
        if (jfBtnModifier.getText().toLowerCase().contains("mettre") == true) {
            System.out.println("Save update");

            String _prenom = jfUserPrenom.getText();
            String _nom = jfUserNom.getText();
            String _email = jfUserEmail.getText();
            String _telephone = jfUserTelephone.getText();
            String _password = jfUserPassword.getText();
            String _role = jfUserRole.getSelectedItem().toString();
            boolean _actif = jfUserActif.isSelected();

            user.setPrenom(_prenom);
            user.setNom(_nom);
            user.setEmail(_email);
            user.setTelephone(_telephone);
            user.setMotDePasse(_password);
            user.setDateCreation(new Date());
            user.setRole(_role);
            
            user.setActive(_actif);

            iu.editUser(user);
            JOptionPane.showMessageDialog(null, "Ustilisateur Modifié");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jfBtnModifier;
    private javax.swing.JCheckBox jfUserActif;
    private javax.swing.JTextPane jfUserEmail;
    private javax.swing.JTextPane jfUserNom;
    private javax.swing.JTextPane jfUserPassword;
    private javax.swing.JTextPane jfUserPrenom;
    private javax.swing.JComboBox<String> jfUserRole;
    private javax.swing.JTextPane jfUserTelephone;
    // End of variables declaration//GEN-END:variables
}
