/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.panels;

import daos.IUtilisateur;
import java.util.Date;
import javax.swing.JOptionPane;
import models.Utilisateurs;
import services.UtilisateurService;

/**
 *
 * @author user
 */
public class UserPanelAdd extends javax.swing.JPanel {

    /**
     * Creates new form User Add Panel
     */
    IUtilisateur iu = new UtilisateurService();
    
    public UserPanelAdd() {
        initComponents();
    }
    
    
    private void AddUser() {
            System.out.println("Add user");

            String _prenom = jfUserPrenom.getText();
            String _nom = jfUserNom.getText();
            String _email = jfUserEmail.getText();
            String _telephone = jfUserTelephone.getText();
            String _password = jfUserPassword.getText();
            String _role = jfUserRole.getSelectedItem().toString().toLowerCase();
            boolean _actif = jfUserActif.isSelected();

            Utilisateurs user = new Utilisateurs();
            user.setPrenom(_prenom);
            user.setNom(_nom);
            user.setEmail(_email);
            user.setTelephone(_telephone);
            user.setMotDePasse(_password);
            user.setDateCreation(new Date());
            user.setRole(_role);
            user.setActive(_actif);

            iu.addRegister(user);
            JOptionPane.showMessageDialog(null, "Utilisateur Ajouté");
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jfUserNom = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jfUserPrenom = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jfUserEmail = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jfUserTelephone = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jfUserRole = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jfUserPassword = new javax.swing.JTextPane();
        jfUserActif = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jfBtnAddUser = new javax.swing.JButton();
        jfBtnEffacer = new javax.swing.JButton();

        jLabel1.setText("Prenom");

        jLabel2.setText("Nom");

        jScrollPane2.setViewportView(jfUserNom);

        jScrollPane3.setViewportView(jfUserPrenom);

        jLabel3.setText("Email");

        jLabel4.setText("Téléphone");

        jScrollPane1.setViewportView(jfUserEmail);

        jScrollPane4.setViewportView(jfUserTelephone);

        jLabel5.setText("Mot de passe");

        jLabel6.setText("Role");

        jfUserRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));

        jScrollPane5.setViewportView(jfUserPassword);

        jfUserActif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfUserActifActionPerformed(evt);
            }
        });

        jLabel7.setText("Compte actif ?");

        jfBtnAddUser.setText("Ajouter");
        jfBtnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfBtnAddUserActionPerformed(evt);
            }
        });

        jfBtnEffacer.setText("Effacer");
        jfBtnEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfBtnEffacerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jfUserActif)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jfUserRole, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jfBtnEffacer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jfBtnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addComponent(jfUserRole, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jfUserActif))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jfBtnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jfBtnEffacer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jfUserActifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfUserActifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfUserActifActionPerformed

    private void jfBtnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfBtnAddUserActionPerformed
        // TODO add your handling code here:
        AddUser();
        cleanUserAddField();
    }//GEN-LAST:event_jfBtnAddUserActionPerformed

    private void jfBtnEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfBtnEffacerActionPerformed
        // TODO add your handling code here:
        cleanUserAddField();
    }//GEN-LAST:event_jfBtnEffacerActionPerformed

    private void cleanUserAddField(){
        jfUserPrenom.setText("");
        jfUserNom.setText("");
        jfUserEmail.setText("");
        jfUserTelephone.setText("");
        jfUserPassword.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jfBtnAddUser;
    private javax.swing.JButton jfBtnEffacer;
    private javax.swing.JCheckBox jfUserActif;
    private javax.swing.JTextPane jfUserEmail;
    private javax.swing.JTextPane jfUserNom;
    private javax.swing.JTextPane jfUserPassword;
    private javax.swing.JTextPane jfUserPrenom;
    private javax.swing.JComboBox<String> jfUserRole;
    private javax.swing.JTextPane jfUserTelephone;
    // End of variables declaration//GEN-END:variables
}
