/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import javax.swing.ImageIcon;

/**
 *
 * @author user
 */
public class CardBox extends javax.swing.JPanel {

    /**
     * Creates new form CardBox
     */
    public CardBox() {
        initComponents();
        setOpaque(false);
        //setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    @Override
    public void paint(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(new Color(75, 242, 140));
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20); // Border-radius de 20 pixels
        
        g2.dispose();
        super.paint(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlEventTitre = new javax.swing.JLabel();
        jlEventImage = new javax.swing.JLabel();
        jlEventDate = new javax.swing.JLabel();
        jlEventLieu = new javax.swing.JLabel();
        jlEventInscrit = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(180, 220));
        setMinimumSize(new java.awt.Dimension(180, 220));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(180, 220));

        jlEventTitre.setText("LES RENCONTRES FISCALES DE DAKAR");

        ImageIcon imageIcon = new javax.swing.ImageIcon(getClass().getResource("/main/images/image4.png"));

        jlEventImage.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                Image image = imageIcon.getImage();
                // Redimensionner l'image en fonction de la taille du JLabel
                Image scaledImage = image.getScaledInstance(jlEventImage.getWidth(), jlEventImage.getHeight(), Image.SCALE_SMOOTH);
                // Créer une nouvelle ImageIcon avec l'image redimensionnée
                ImageIcon scaledImageIcon = new ImageIcon(scaledImage);
                jlEventImage.setIcon(scaledImageIcon);
                jlEventImage.setIcon(scaledImageIcon);
            }
        });
        jlEventImage.setMaximumSize(new java.awt.Dimension(180, 110));
        jlEventImage.setMinimumSize(new java.awt.Dimension(180, 110));
        jlEventImage.setName(""); // NOI18N

        jlEventDate.setText("sam., avr. 29, 09:00");

        jlEventLieu.setText("Radisson Blu Hotel • Dakar, Dakar Libre");

        jlEventInscrit.setText("9 inscrits");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlEventImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlEventTitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlEventDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlEventLieu, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jlEventInscrit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jlEventImage, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlEventTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlEventDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlEventLieu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlEventInscrit)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlEventDate;
    private javax.swing.JLabel jlEventImage;
    private javax.swing.JLabel jlEventInscrit;
    private javax.swing.JLabel jlEventLieu;
    private javax.swing.JLabel jlEventTitre;
    // End of variables declaration//GEN-END:variables
}
